#!/bin/bash
set -v
# last edited 30 sept 2016
pkill sw1_1h
pkill geyser

curl http://192.168.0.31/relay/off
curl http://192.168.0.32/relay/off
curl http://192.168.0.33/relay/off
curl http://192.168.0.41/relay/off
